# Generated by Django 6.1.1 on 2026-09-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_employeeprofile_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='max_id',
        ),
    ]
